stages:
  - check
  - deploy

variables:
  HAS_BREAKING_CHANGE: "false" # Default to false

check_breaking_change:
  stage: check
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    # Fetch commit messages
    - git fetch --no-tags --quiet
    - BREAKING_CHANGE_FOUND=$(git log -1 --pretty=%B | grep -q "BREAKING_CHANGE" && echo "true" || echo "false")
    - echo "BREAKING_CHANGE_FOUND=$BREAKING_CHANGE_FOUND"
    - echo "HAS_BREAKING_CHANGE=$BREAKING_CHANGE_FOUND" >> .env # Pass to next job

  artifacts:
    reports:
      dotenv: .env # Make the variable available in subsequent stages

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying..."
  rules:
    - if: '$HAS_BREAKING_CHANGE == "true"' # Run only if BREAKING_CHANGE is found
    - if: '$HAS_BREAKING_CHANGE == "false"' # Run otherwise