"""
    A module that exposes a class for interacting with a Llama3 model via Amazon Bedrock.

    Classes
    ----------
    Llama3Handler
        A class to handle prompts being sent to and messages received from the Llama3 model.
"""

import logging
from typing import Dict
from langchain_aws import (
    BedrockLLM,
)  # Use BedrockLLM over BedrockChat for more control (e.g., use System Prompts)
from model.aws import aws_helpers
from config import get_settings


logger = logging.getLogger(__name__)


class GuardrailsFilterError(Exception):
    """
    A custom exception class to be raised when Bedrock Guardrails content filters are hit.

    Attributes
    ----------
    GUARDRAILS_ERROR_MSG : str
        A message indicating that the request/response has been blocked by Guardrails.
    UNPROCESSABLE_ERROR_CODE : int
        An error code indicating that the request could not be processed.

    Methods
    -------
    __init__()
        Initializes the exception with the default error message and error code.
    """

    GUARDRAILS_ERROR_MSG = (
        "Guardrails have blocked the request/response. Request could not be processed."
    )
    UNPROCESSABLE_ERROR_CODE = 422

    def __init__(self):
        self.message = self.GUARDRAILS_ERROR_MSG
        self.error_code = self.UNPROCESSABLE_ERROR_CODE
        super().__init__(self.message)


class PromptBlockedError(GuardrailsFilterError):
    """
    A custom exception class to be raised when Bedrock Guardrails content filters block a prompt
    (prompt/input sent to the LLM).

    Attributes
    ----------
    GUARDRAILS_ERROR_MSG : str
        A message indicating that the prompt has been blocked by Guardrails.
    UNPROCESSABLE_ERROR_CODE : int
        An error code indicating that the request could not be processed.
    """

    GUARDRAILS_ERROR_MSG = "Guardrails have blocked the prompt sent to the model. Request could not be processed."
    UNPROCESSABLE_ERROR_CODE = 422


class ResponseBlockedError(GuardrailsFilterError):
    """
    A custom exception class to be raised when Bedrock Guardrails content filters block a response
    (a response/output that was generated by an LLM).

    Attributes
    ----------
    GUARDRAILS_ERROR_MSG : str
        A message indicating that the response has been blocked by Guardrails.
    UNPROCESSABLE_ERROR_CODE : int
        An error code indicating that the request could not be processed.
    """

    GUARDRAILS_ERROR_MSG = "Guardrails have blocked the response generated by the model. Request could not be processed."
    UNPROCESSABLE_ERROR_CODE = 422


# Setup the handler for transforming LLM inputs/outputs
class Llama3Handler:
    """
    A class to handle prompts being sent and messages received from the Llama3 model.

    # Methods

    ## __init__(llm_config: Dict)
        Initializes the Llama3Handler with the given configuration.
    - llm_config should include:
        - model_id (str): The ID of the Bedrock Llama3 model to use
        - model_kwargs (dict): Dictionary to define model parameters
            - temperature (float): Temperature Parameter
            - top_p (float): Top P Parameter
            - max_gen_len (int): Max output tokens to generate (max 2048)
        - guardrail (dict, optional): Dictionary to define the guardrail configuration
            - Dictionary should contain:
                - guardrailIdentifier (str): ID of the guardrail configuration
                - guardrailVersion (str): Version of the guardrail configuration
                - blocked_prompt_msg (str): The string returned from Bedrock when prompt
                    guardrails are activated (default message, blocking an input prompt from being
                    sent to Llama3). Configured in Bedrock when setting up a guardrail.
                - blocked_response_msg (str): The string returned from Bedrock when response
                    guardrails are activated (default message, blocking a generated response from
                    being returned from Llama3). Configured in Bedrock when setting up a guardrail.

    ## invoke(user_prompt, system_prompt="", assistant_prompt="")
        Invoke the llama3 model with the given prompts and return the response.
    """

    CONTENT_TYPE = "application/json"
    ACCEPTS = "application/json"

    BEGIN_TEXT = "<|begin_of_text|>"

    START_HEAD = "<|start_header_id|>"
    END_HEAD = "<|end_header_id|>\n\n"
    END_TEXT = "<|eot_id|>"

    # Roles
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"

    # Guardrail IDs
    GUARDRAIL = "guardrail"
    BLOCKED_PROMPT_MSG_ID = "blocked_prompt_msg"
    BLOCKED_RESPONSE_MSG_ID = "blocked_response_msg"

    def __init__(self, llm_config: Dict):
        client = aws_helpers.get_client("bedrock-runtime")

        if not hasattr(self, "_llm_config"):
            self._llm_config = llm_config

        self.client = client
        self.model_id = llm_config["model_id"]
        self.model_kwargs = llm_config["model_kwargs"]
        self.update_guardrail_config()

    def update_guardrail_config(self):
        """
        Fetch the latest guardrail ID and version from environment variables
        """
        client = aws_helpers.get_client("bedrock-runtime")
        self.client = client

        self.blocked_prompt_msg = (
            get_settings().bedrock_guardrail_blocked_prompt_message
        )
        self.blocked_response_msg = (
            get_settings().bedrock_guardrail_blocked_response_message
        )
        harms_guardrail = {
            "guardrailIdentifier": get_settings().bedrock_harms_guardrail_id,
            "guardrailVersion": get_settings().bedrock_harms_guardrail_version,
        }
        self.llm = BedrockLLM(
            client=self.client,
            model_id=self.model_id,
            model_kwargs=self.model_kwargs,
            provider="meta",
            guardrails=harms_guardrail,
        )
        logger.debug("Updated Guardrail Config: %s", harms_guardrail)

    def __format_prompt(self, role, prompt, close_input: bool = True):
        """
        Format a prompt with a role, as required for Llama3.

        Args:
            self: The object instance.
            role (str): The role of the prompt (e.g., 'user' or 'assistant').
            prompt (str): The main text of the prompt.
            close_input (bool, optional): Whether to add closing text to the prompt. Default = True.

        Returns:
            str: The formatted prompt with role and optional closing text.
        """
        formatted_prompt = self.START_HEAD + role + self.END_HEAD + prompt
        # Sometimes, we don't want to 'END' the prompt (e.g., for leading into the assistant prompt)
        if close_input:
            formatted_prompt += self.END_TEXT
        return formatted_prompt

    def __format_llama3_input(
        self,
        user_prompt: str,
        system_prompt: str,
        assistant_prompt: str,
        few_shots: list = None,
    ) -> str:
        """
        Format the input for the llama3 model by combining the user, system, and assistant prompts.

        Args:
            self: The object instance.
            user_prompt (str): The user prompt to be formatted.
            system_prompt (str): The system prompt to be formatted.
            assistant_prompt (str): The assistant prompt to be formatted.
            few_shots (list(tuple(str))): User and assistant prompts to act as few-shot examples.

        Returns:
            str: The formatted input for the llama3 model.

        If no system prompt is provided, the system input will be empty.
        The user input and assistant input are always included in the formatted input.
        """

        if system_prompt != "":
            system_input = self.__format_prompt(self.SYSTEM, system_prompt)
        else:
            system_input = system_prompt

        formatted_few_shot_inputs = ""
        if few_shots:
            for shot in few_shots:
                user_shot_prompt = shot[self.USER]
                user_shot_input = self.__format_prompt(self.USER, user_shot_prompt)
                assistant_shot_prompt = shot[self.ASSISTANT]
                assistant_shot_input = self.__format_prompt(
                    self.ASSISTANT, assistant_shot_prompt
                )
                formatted_few_shot_inputs += user_shot_input + assistant_shot_input

        user_input = self.__format_prompt(self.USER, user_prompt)

        # If no specific assistant prompt provided (""), we still need the assistant input
        assistant_input = self.__format_prompt(self.ASSISTANT, assistant_prompt, False)

        llama3_input = (
            self.BEGIN_TEXT
            + system_input
            + formatted_few_shot_inputs
            + user_input
            + assistant_input
        )

        return llama3_input

    def format_one_shot(self, user_prompt, assistant_prompt):
        return {self.USER: user_prompt, self.ASSISTANT: assistant_prompt}

    def invoke(
        self,
        user_prompt: str,
        system_prompt: str = "",
        assistant_prompt: str = "",
        few_shots: list = None,
    ) -> str:
        """
        Invoke the llama3 model with the given prompts and return the response.

        Args:
            user_prompt (str): The user prompt.
            system_prompt (str): The system prompt.
            assistant_prompt (str): The assistant prompt (to begin generation).
            few_shots (list(tuple(str))): User and assistant prompts to act as few-shot examples.

        Returns:
            str: The response from the llama3 model after invoking with the formatted prompt.
        """
        self.update_guardrail_config()

        formatted_prompt = self.__format_llama3_input(
            user_prompt, system_prompt, assistant_prompt, few_shots
        )
        # self.__init__(self._llm_config)
        response = self.llm.invoke(formatted_prompt)
        if self.blocked_prompt_msg is not None and response == self.blocked_prompt_msg:
            raise PromptBlockedError()
        if (
            self.blocked_response_msg is not None
            and response == self.blocked_response_msg
        ):
            raise ResponseBlockedError()
        return response
